// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HieuLe.Kafka.Example.Microservice.Shared.Dtos
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Order : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Order"",""namespace"":""HieuLe.Kafka.Example.Microservice.Shared.Dtos"",""fields"":[{""name"":""id"",""type"":""string""},{""name"":""customerId"",""type"":""long""},{""name"":""state"",""type"":{""type"":""enum"",""name"":""OrderState"",""namespace"":""HieuLe.Kafka.Example.Microservice.Shared.Dtos"",""symbols"":[""CREATED"",""VALIDATED"",""FAILED"",""SHIPPED""]}},{""name"":""product"",""type"":{""type"":""enum"",""name"":""Product"",""namespace"":""HieuLe.Kafka.Example.Microservice.Shared.Dtos"",""symbols"":[""JUMPERS"",""UNDERPANTS"",""STOCKINGS""]}},{""name"":""quantity"",""type"":""int""},{""name"":""price"",""type"":""double""}]}");
		private string _id;
		private long _customerId;
		private HieuLe.Kafka.Example.Microservice.Shared.Dtos.OrderState _state;
		private HieuLe.Kafka.Example.Microservice.Shared.Dtos.Product _product;
		private int _quantity;
		private double _price;
		public virtual Schema Schema
		{
			get
			{
				return Order._SCHEMA;
			}
		}
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public long customerId
		{
			get
			{
				return this._customerId;
			}
			set
			{
				this._customerId = value;
			}
		}
		public HieuLe.Kafka.Example.Microservice.Shared.Dtos.OrderState state
		{
			get
			{
				return this._state;
			}
			set
			{
				this._state = value;
			}
		}
		public HieuLe.Kafka.Example.Microservice.Shared.Dtos.Product product
		{
			get
			{
				return this._product;
			}
			set
			{
				this._product = value;
			}
		}
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				this._quantity = value;
			}
		}
		public double price
		{
			get
			{
				return this._price;
			}
			set
			{
				this._price = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.customerId;
			case 2: return this.state;
			case 3: return this.product;
			case 4: return this.quantity;
			case 5: return this.price;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.String)fieldValue; break;
			case 1: this.customerId = (System.Int64)fieldValue; break;
			case 2: this.state = (HieuLe.Kafka.Example.Microservice.Shared.Dtos.OrderState)fieldValue; break;
			case 3: this.product = (HieuLe.Kafka.Example.Microservice.Shared.Dtos.Product)fieldValue; break;
			case 4: this.quantity = (System.Int32)fieldValue; break;
			case 5: this.price = (System.Double)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
