// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HieuLe.Kafka.Example.Microservice.OrderService.Domains.Dtos
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class OrderValue : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""OrderValue"",""namespace"":""HieuLe.Kafka.Example.Microservice.OrderService.Domains.Dtos"",""fields"":[{""name"":""order"",""type"":{""type"":""record"",""name"":""Order"",""namespace"":""HieuLe.Kafka.Example.Microservice.OrderService.Domains.Dtos"",""fields"":[{""name"":""id"",""type"":""string""},{""name"":""customerId"",""type"":""long""},{""name"":""state"",""type"":{""type"":""enum"",""name"":""OrderState"",""namespace"":""HieuLe.Kafka.Example.Microservice.OrderService.Domains.Dtos"",""symbols"":[""CREATED"",""VALIDATED"",""FAILED"",""SHIPPED""]}},{""name"":""product"",""type"":{""type"":""enum"",""name"":""Product"",""namespace"":""HieuLe.Kafka.Example.Microservice.OrderService.Domains.Dtos"",""symbols"":[""JUMPERS"",""UNDERPANTS"",""STOCKINGS""]}},{""name"":""quantity"",""type"":""int""},{""name"":""price"",""type"":""double""}]}},{""name"":""value"",""type"":""double""}]}");
		private HieuLe.Kafka.Example.Microservice.OrderService.Domains.Dtos.Order _order;
		private double _value;
		public virtual Schema Schema
		{
			get
			{
				return OrderValue._SCHEMA;
			}
		}
		public HieuLe.Kafka.Example.Microservice.OrderService.Domains.Dtos.Order order
		{
			get
			{
				return this._order;
			}
			set
			{
				this._order = value;
			}
		}
		public double @value
		{
			get
			{
				return this._value;
			}
			set
			{
				this._value = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.order;
			case 1: return this.@value;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.order = (HieuLe.Kafka.Example.Microservice.OrderService.Domains.Dtos.Order)fieldValue; break;
			case 1: this.@value = (System.Double)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
