// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Schemas/order.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages {

  /// <summary>Holder for reflection information generated from Schemas/order.proto</summary>
  public static partial class OrderReflection {

    #region Descriptor
    /// <summary>File descriptor for Schemas/order.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OrderReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNTY2hlbWFzL29yZGVyLnByb3RvEgZzaGFyZWQilAIKBU9yZGVyEgoKAmlk",
            "GAEgASgJEhMKC2N1c3RvbWVyX2lkGAIgASgDEicKBXN0YXRlGAMgASgOMhgu",
            "c2hhcmVkLk9yZGVyLk9yZGVyU3RhdGUSJgoHcHJvZHVjdBgEIAEoDjIVLnNo",
            "YXJlZC5PcmRlci5Qcm9kdWN0EhAKCHF1YW50aXR5GAUgASgFEg0KBXByaWNl",
            "GAYgASgBIkEKCk9yZGVyU3RhdGUSCwoHQ1JFQVRFRBAAEg0KCVZBTElEQVRF",
            "RBABEgoKBkZBSUxFRBACEgsKB1NISVBQRUQQAyI1CgdQcm9kdWN0EgsKB0pV",
            "TVBFUlMQABIOCgpVTkRFUlBBTlRTEAESDQoJU1RPQ0tJTkdTEAJCOaoCNkhp",
            "ZXVMZS5LYWZrYS5FeGFtcGxlLk1pY3Jvc2VydmljZS5TaGFyZWQuUHJvdG9N",
            "ZXNzYWdlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order), global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Parser, new[]{ "Id", "CustomerId", "State", "Product", "Quantity", "Price" }, null, new[]{ typeof(global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.OrderState), typeof(global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.Product) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Order : pb::IMessage<Order>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Order> _parser = new pb::MessageParser<Order>(() => new Order());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Order> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.OrderReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Order() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Order(Order other) : this() {
      id_ = other.id_;
      customerId_ = other.customerId_;
      state_ = other.state_;
      product_ = other.product_;
      quantity_ = other.quantity_;
      price_ = other.price_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Order Clone() {
      return new Order(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "customer_id" field.</summary>
    public const int CustomerIdFieldNumber = 2;
    private long customerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CustomerId {
      get { return customerId_; }
      set {
        customerId_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 3;
    private global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.OrderState state_ = global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.OrderState.Created;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.OrderState State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "product" field.</summary>
    public const int ProductFieldNumber = 4;
    private global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.Product product_ = global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.Product.Jumpers;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.Product Product {
      get { return product_; }
      set {
        product_ = value;
      }
    }

    /// <summary>Field number for the "quantity" field.</summary>
    public const int QuantityFieldNumber = 5;
    private int quantity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Quantity {
      get { return quantity_; }
      set {
        quantity_ = value;
      }
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 6;
    private double price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Order);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Order other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (CustomerId != other.CustomerId) return false;
      if (State != other.State) return false;
      if (Product != other.Product) return false;
      if (Quantity != other.Quantity) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Price, other.Price)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (CustomerId != 0L) hash ^= CustomerId.GetHashCode();
      if (State != global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.OrderState.Created) hash ^= State.GetHashCode();
      if (Product != global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.Product.Jumpers) hash ^= Product.GetHashCode();
      if (Quantity != 0) hash ^= Quantity.GetHashCode();
      if (Price != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Price);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (CustomerId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(CustomerId);
      }
      if (State != global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.OrderState.Created) {
        output.WriteRawTag(24);
        output.WriteEnum((int) State);
      }
      if (Product != global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.Product.Jumpers) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Product);
      }
      if (Quantity != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Quantity);
      }
      if (Price != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(Price);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (CustomerId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(CustomerId);
      }
      if (State != global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.OrderState.Created) {
        output.WriteRawTag(24);
        output.WriteEnum((int) State);
      }
      if (Product != global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.Product.Jumpers) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Product);
      }
      if (Quantity != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Quantity);
      }
      if (Price != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(Price);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (CustomerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CustomerId);
      }
      if (State != global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.OrderState.Created) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (Product != global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.Product.Jumpers) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Product);
      }
      if (Quantity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quantity);
      }
      if (Price != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Order other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.CustomerId != 0L) {
        CustomerId = other.CustomerId;
      }
      if (other.State != global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.OrderState.Created) {
        State = other.State;
      }
      if (other.Product != global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.Product.Jumpers) {
        Product = other.Product;
      }
      if (other.Quantity != 0) {
        Quantity = other.Quantity;
      }
      if (other.Price != 0D) {
        Price = other.Price;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            CustomerId = input.ReadInt64();
            break;
          }
          case 24: {
            State = (global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.OrderState) input.ReadEnum();
            break;
          }
          case 32: {
            Product = (global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.Product) input.ReadEnum();
            break;
          }
          case 40: {
            Quantity = input.ReadInt32();
            break;
          }
          case 49: {
            Price = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            CustomerId = input.ReadInt64();
            break;
          }
          case 24: {
            State = (global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.OrderState) input.ReadEnum();
            break;
          }
          case 32: {
            Product = (global::HieuLe.Kafka.Example.Microservice.Shared.ProtoMessages.Order.Types.Product) input.ReadEnum();
            break;
          }
          case 40: {
            Quantity = input.ReadInt32();
            break;
          }
          case 49: {
            Price = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Order message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum OrderState {
        [pbr::OriginalName("CREATED")] Created = 0,
        [pbr::OriginalName("VALIDATED")] Validated = 1,
        [pbr::OriginalName("FAILED")] Failed = 2,
        [pbr::OriginalName("SHIPPED")] Shipped = 3,
      }

      public enum Product {
        [pbr::OriginalName("JUMPERS")] Jumpers = 0,
        [pbr::OriginalName("UNDERPANTS")] Underpants = 1,
        [pbr::OriginalName("STOCKINGS")] Stockings = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
